woorifisa-projects-3rd/WithBeeTravel-BE

.github/workflows/gradle.yml, .gitignore, src/main/resources/application.properties
=> [build] rds 연동 및 환경변수 설정

.github/workflows/deploy.yml
- main에 푸시나 머지될 때만 워크플로우 실행 되어 CI/CD 진행되게 설정 바꿨습니다.
=> [fix]: 워크플로우 수정(main에 push 되거나 merge될 때 실행)

src/main/java/withbeetravel/domain/Account.java, src/main/java/withbeetravel/domain/History.java, src/main/java/withbeetravel/domain/PaymentParticipatedMember.java, src/main/java/withbeetravel/domain/Product.java, src/main/java/withbeetravel/domain/SettlementRequest.java, src/main/java/withbeetravel/domain/SettlementRequestLog.java, src/main/java/withbeetravel/domain/SharedPayment.java, src/main/java/withbeetravel/domain/Travel.java, src/main/java/withbeetravel/domain/TravelCountry.java, src/main/java/withbeetravel/domain/TravelMember.java, src/main/java/withbeetravel/domain/TravelMemberSettlementHistory.java, src/main/java/withbeetravel/domain/User.java
- close #28 
- 기존 엔티티에 Banking 서버의 엔티티를 합쳤습니다.
- 피드백 부탁드려요!
=> [feat/TK-69]: Entity 수정

build.gradle, src/main/java/withbeetravel/config/SecurityConfig.java, src/main/java/withbeetravel/config/SwaggerConfig.java, src/main/java/withbeetravel/controller/PaymentController.java, src/main/java/withbeetravel/controller/docs/PaymentControllerDocs.java, src/main/java/withbeetravel/dto/ChooseParticipantsRequestDto.java, src/main/java/withbeetravel/dto/SuccessResponseDto.java, src/main/java/withbeetravel/exception/dto/ErrorResponseDto.java
- close #32 
- swagger 설정
- https://happybplus.tistory.com/1057 참고
=> Feat/TK-117 swagger 설정

src/main/java/withbeetravel/domain/LogTitle.java, src/main/java/withbeetravel/domain/SettlementRequestLog.java, src/main/java/withbeetravel/domain/SharedPayment.java
- SharedPayment, SettlementRequestLog 엔티티 수정
- 세부지출내역 구현하다가 먼저 엔티티를 수정해야할 거 같아서 올립니다!
=> [fix] 엔티티 수정

src/main/java/withbeetravel/domain/SharedPayment.java
- SharedPayment 엔티티 수정
- 누락된 부분 다시 수정해서 올려요!
=> [refactor]: 엔티티 수정

src/main/java/withbeetravel/dto/response/SuccessResponse.java
- close #40 
- 성공 응답에 사용할 CustomResponseDTO를 생성하였습니다.
- postman 예시
- 개발회고에 사용법 작성해두었습니다!
=> [feat/TK-132]: 커스텀 Response DTO 추가

.gitignore, build.gradle, src/main/java/withbeetravel/WithbeetravelApplication.java, src/main/java/withbeetravel/config/S3Config.java, src/main/java/withbeetravel/service/S3Uploader.java
- close #44 
- S3 연동
- S3에 이미지 업로드, 업데이트, 삭제 기능 추가
- 사용 방법은 회고에 정리해놓겠습니다.
=> Feat/tk 135 s3 연동

src/main/java/withbeetravel/domain/TravelMember.java
- change client id
- 내용을 적어주세요.
=> [fix/dev]: TravelMember 엔티티 수정

src/main/java/withbeetravel/domain/User.java
-TK-172
- 유저엔티티에 핀번호 실패 횟수 저장할 칼럼과 
- 5회이상 핀번호 실패 시 상태 저장할 칼럼 추가
- 
=> [feat/TK-174]: 유저 엔티티에 칼럼 추가

src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java
-컴플리트 해결하다가 미처 못바꾼 하나.
- 뱅킹 에러처리 하는 부분에서 오류난 부분 수정
- 
-
=> [hotfix]: 뱅킹 에러코드 컴플리트 해결

src/main/java/withbeetravel/domain/User.java
- 유저 엔티티에 핀번호 검증을 위한 칼럼 추가
- 했숨다
=> [hotfix]: 회원 엔티티에 핀번호 관련 칼럼 추가

src/main/java/withbeetravel/exception/error/BankingErrorCode.java
- change client id
- 내용을 적어주세요.
=> [hotfix]: 뱅킹에러코드 정상화

src/main/java/withbeetravel/controller/settlement/SettlementController.java, src/main/java/withbeetravel/domain/TravelMember.java, src/main/java/withbeetravel/domain/User.java, src/main/java/withbeetravel/exception/error/BankingErrorCode.java, src/main/java/withbeetravel/repository/TravelMemberSettlementHistoryRepository.java, src/main/java/withbeetravel/service/banking/AccountServiceImpl.java, src/main/java/withbeetravel/service/settlement/SettlementService.java, src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
- close #76 
- 정산 취소 API 구현하였습니다.
- 정산 처리 로직 중 수정할 부분이 있어서 같이 올렸습니다. 메서드를 잘못 썼더라구요 헿😳😳
- 정산 취소 성공시 
- 정산 요청 후 취소 시 db 변경 상황
- 피드백 부탁드려요~
=> [Feat/TK-168] 정산 취소 API 구현

src/main/java/withbeetravel/controller/travel/TravelController.java, src/main/java/withbeetravel/domain/Account.java, src/main/java/withbeetravel/dto/request/account/CardCompletedRequest.java, src/main/java/withbeetravel/service/travel/TravelService.java, src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
- #118 
- 카드 발급 여부 API 구현 
- useId불러오는 방식 수정 
- 카드 발급 여부 API 구현 
- useId불러오는 방식 수정 
- 피드백 주시면 감사하겠습니다~
=> [Feat/tk 208] - 카드 발급 여부 api 구현 

src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java
=> Feat/tk 207 위비 카드 결제 내역 날짜 오름차순 정렬 추가

src/main/java/withbeetravel/controller/payment/SharedPaymentRegisterController.java, src/main/java/withbeetravel/controller/payment/docs/SharedPaymentRegisterControllerDocs.java, src/main/java/withbeetravel/dto/response/payment/CurrencyUnitResponse.java, src/main/java/withbeetravel/repository/TravelCountryRepository.java, src/main/java/withbeetravel/service/payment/SharedPaymentRegisterService.java, src/main/java/withbeetravel/service/payment/SharedPaymentRegisterServiceImpl.java
- close #123 
- 통화 코드 리스트 불러오기 API 구현
- 방문 나라에서 사용하는 통화 코드를 우선으로 통화 코드 목록 불러오기
- 원화는 항상 가장 앞에 위치
- 국내 여행
- 해외 여행
=> [feat/TK-213]: 통화 코드 리스트 불러오기 API 구현

src/main/java/withbeetravel/controller/payment/SharedPaymentRecordController.java, src/main/java/withbeetravel/service/payment/SharedPaymentRecordService.java, src/main/java/withbeetravel/service/payment/SharedPaymentRecoredServiceImpl.java
- close #129 
- 여행 기록 추가/수정 API 에러 수정
- 여행 기록 추가/수정 API 에러 수정
- 여행 기록 관련 서비스 리턴 값 수정
=> [hotfix/TK-220]: 여행 기록 추가/수정 API 에러 수정

.github/workflows/depoly-desktop.yml, src/main/java/withbeetravel/DataLoader.java, src/main/java/withbeetravel/controller/banking/AccountController.java, src/main/java/withbeetravel/domain/User.java, src/main/java/withbeetravel/service/banking/AccountServiceImpl.java
- close #120 
- htts 적용완료(aws에서 작없해서 코드 변경사항은 거의 없음)
-  User엔티티에서 비밀번호 저장 할 때 암호화해서 저장 
-  dev에 push 될 때 CI/CD 되게 설정 변경
-  DATALOADER들어가 있는데 컴포넌트 스캔 빼놨음(넣으면 안됩니다.)
=> Feat/tk 210 https 연결

src/main/java/withbeetravel/controller/travel/TravelController.java, src/main/java/withbeetravel/domain/TravelMember.java, src/main/java/withbeetravel/dto/response/travel/TravelHomeResponse.java, src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java, src/main/java/withbeetravel/service/travel/TravelService.java, src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
- close #96
- TravelHomeResponse에 이 필드들 추가
```
@Schema(description = "여행 멤버 리스트")
private List<TravelMemberResponse> travelMembers;
@Schema(description = "본인이 그룹장인지 여부")
private boolean isCaptain;
@Schema(description = "정산이 진행 중인지 여부")
private SettlementStatus settlementStatus;
@Schema(description = "정산 내역에 동의했는지 여부")
private Boolean isAgreed;
```
- 응답값
```
{
"status": 200,
"message": "여행 홈 데이터 불러오기 성공",
"data": {
"id": 1,
"travelName": "초루의 유럽 여행",
"travelStartDate": "2024-06-01",
"travelEndDate": "2024-06-07",
"isDomesticTravel": false,
"countries": [
"이탈리아",
"독일"
],
"mainImage": null,
"statistics": {
"숙박": 41.6,
"쇼핑": 20.8,
"식비": 37.6
},
"travelMembers": [
{
"id": 1,
"name": "이도이",
"profileImage": 1
},
{
"id": 2,
"name": "공소연",
"profileImage": 2
},
{
"id": 3,
"name": "유승아", …
```
=> [feat/TK-183]: 여행 홈 API 필드 추가

src/main/java/withbeetravel/domain/User.java
- password에 BCrypt.hashpw(password, BCrypt.gensalt()) 삭제
=> [Feat/TK-215]: User 엔티티 수정

src/main/java/withbeetravel/aspect/BankingAccessAspect.java, src/main/java/withbeetravel/controller/banking/HistoryController.java, src/main/java/withbeetravel/controller/banking/docs/HistoryControllerDocs.java, src/main/java/withbeetravel/dto/request/account/HistoryRequest.java, src/main/java/withbeetravel/service/banking/HistoryService.java, src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java, src/main/java/withbeetravel/service/payment/SharedPaymentRegisterService.java, src/main/java/withbeetravel/service/payment/SharedPaymentRegisterServiceImpl.java
- close #136 
- 위비 카드 결제 내역 추가 시 공동 결제 내역에 자동 추가되는 로직 구현
- 위비 카드 결제 내역 추가 시 공동 결제 내역에 자동 추가되는 로직 구현
=> [feat/TK-228]: 위비 카드 결제 내역 추가 시 공동 결제 내역에 자동 추가되는 로직 구현

src/main/java/withbeetravel/controller/banking/AccountController.java
-
- AOP 잘못된 사항 수정
- 내용을 적어주세요.
=> Feat/tk 224 관리자 페이지 api 구현

.github/workflows/depoly-desktop.yml, src/main/java/withbeetravel/controller/banking/AccountController.java
- 
- cicd 안전(?)하게 하도록 변경 완료
- 
- 
=> Feat/tk 224 ci/cd 수정

src/main/java/withbeetravel/DataLoader.java, src/main/java/withbeetravel/controller/travel/TravelController.java, src/main/java/withbeetravel/domain/User.java, src/main/java/withbeetravel/repository/AccountRepository.java, src/main/java/withbeetravel/service/banking/AccountServiceImpl.java, src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
- #124 
- 여행 생성 시 트래블멤버에 트래블 추가 
- 여행 생성 시 트래블멤버에 트래블 추가
-  언제나 감사합니다,...
=> [Feat/tk 214] - 코드 리팩토링 

src/test/java/withbeetravel/service/settlement/SettlementServiceTest.java, src/test/java/withbeetravel/support/AccountFixture.java, src/test/java/withbeetravel/support/SettlementRequestFixture.java, src/test/java/withbeetravel/support/SettlementRequestLogFixture.java, src/test/java/withbeetravel/support/SharedPaymentFixture.java, src/test/java/withbeetravel/support/TravelFixture.java, src/test/java/withbeetravel/support/UserFixture.java
- 테스트 코드 Fixture 작성하였습니다.
- 필요시 더 추가하시면 됩니다.
- 예시로 정산 요청 서비스 테스트 코드를 작성해보려고 했는데 생각보다 오래 걸리네요 ㅠ ㅠ 미완성이지만 일단 업로드하겠습니다!
=> [Feat/TK-253] 테스트 코드 Fixture 작성

src/main/java/withbeetravel/config/CorsConfig.java
=> [Feat/tk 253] CorsConfig 수정

src/main/java/withbeetravel/config/CorsConfig.java
=> [feat/TK-253] CorsConfig 수정

src/main/java/withbeetravel/config/CorsConfig.java
=> Feat/tk 253 테스트 코드 작성

src/main/java/withbeetravel/config/S3Config.java
- 
- S3설정 파일 수정(IAM ROLE 적용 되게)
- 내용을 적어주세요.
=> [feat/TK-224]:S3Config 설정 변경

src/main/java/withbeetravel/controller/settlement/SettlementRequestLogController.java
=> [refactor/TK-253] Sse controller 수정

src/main/java/withbeetravel/controller/settlement/SettlementRequestLogController.java
=> [Feat/TK-253] sse 컨트롤러 수정

build.gradle, src/main/java/withbeetravel/DataLoader.java, src/main/java/withbeetravel/domain/LogTitle.java, src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java, src/main/java/withbeetravel/service/travel/TravelServiceImpl.java, src/test/java/withbeetravel/controller/BaseIntegrationTest.java, src/test/java/withbeetravel/controller/settlement/SettlementControllerTest.java, src/test/java/withbeetravel/service/auth/AuthServiceTest.java, src/test/java/withbeetravel/service/settlement/SettlementServiceTest.java, src/test/java/withbeetravel/support/BaseIntegrationTest.java, src/test/java/withbeetravel/support/SettlementTestFixture.java, src/test/java/withbeetravel/support/TestData.java
- close #147 
- 정산 단위, 통합 테스트 코드 작성
- 실시간 알림 수정 (정산 완료 시 허니 캡슐로 이동, 친구 초대 시 알림 전송, 위비 지원금 0원일 때 메시지 수정, 정산 요청 시 여행장 제외하고 정산 요청 알림 전송)
- 통합 테스트용으로 제가 작성한 `controller` 테스트 예시 참고하시면 좋을 것 같습니다! (`gradle` 재빌드하세용!)
=> [Feat/TK-253] 정산 관련 테스트 코드 작성 및 API 수정

src/test/java/withbeetravel/service/travel/TravelServiceImplTest.java
- #165 
- 여행 서비스 테스트 코드 작성
- 여행 서비스 테스트 코드 작성
=> [feat/TK-264]:여행 서비스 테스트 코드 작성

.github/workflows/depoly-desktop.yml
=> Feat/tk 273 CI/CD 설정 수정 -테스트 코드

src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
=> [refactor/TK-253] 여행 멤버 초대 코드 알림 추가

src/main/java/withbeetravel/DataLoader.java, src/main/java/withbeetravel/controller/travel/TravelController.java, src/main/java/withbeetravel/controller/travel/docs/TravelControllerDocs.java, src/main/java/withbeetravel/dto/response/travel/HoneyCapsuleResponse.java, src/main/java/withbeetravel/service/payment/SharedPaymentRecordServiceImpl.java, src/main/java/withbeetravel/service/payment/SharedPaymentRegisterServiceImpl.java, src/main/java/withbeetravel/service/travel/TravelService.java, src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
- 허니 캡슐에 추가한 멤버 프로필 이미지 추가
- 여행 메인 이미지 변경 API 추가
=> Feat/tk 260 허니 캡슐에 추가한 멤버 프로필 이미지 추가

src/main/java/withbeetravel/dto/request/account/CreateAccountRequest.java, src/main/java/withbeetravel/exception/error/AuthErrorCode.java, src/main/java/withbeetravel/repository/AccountRepository.java, src/main/java/withbeetravel/service/auth/AuthServiceImpl.java
=> [Feat/TK-253] 회원가입 수정

src/main/java/withbeetravel/scheduler/SettlementRequestLogScheduler.java
=> [refactor/TK-253] 스케줄러 테스트용으로 수정

src/main/java/withbeetravel/service/travel/HoneyCapsuleServiceImpl.java
- 허니캡슐 여행 기록 없는 결제 내역까지 불려오는 에러 수정
=> [fix/TK-275]: 허니캡슐 여행 기록 없는 결제 내역까지 불려오는 에러 수정

src/main/java/withbeetravel/scheduler/SettlementRequestLogScheduler.java, src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
- 영상 촬영 때문에 수정한 스케줄러 코드 원상복구
- 내용을 적어주세요.
=> [Feat/TK-253] 스케줄러 코드 수정

src/main/java/withbeetravel/service/banking/AccountServiceImpl.java, src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java
- 송금 받았을 때, 결제 내역 추가할 때 SSE 알림
- 내용을 적어주세요.
=> [feat/TK-273] :뱅킹 SSE 설정

src/main/java/withbeetravel/domain/LogTitle.java, src/main/java/withbeetravel/service/banking/AccountServiceImpl.java, src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
=> Feat/tk 273 카카오톡 초대코드 api 수정

.github/workflows/depoly-desktop.yml
=> [feat/TK-253] cicd 수정

src/main/java/withbeetravel/domain/PaymentParticipatedMember.java, src/main/java/withbeetravel/domain/SharedPayment.java, src/test/java/withbeetravel/service/payment/SharedPaymentServiceImplTest.java
- close #159
- 공동지출내역 테스트 코드 작성
- 리뷰 부탁드려요!!
=> [feat/TK-262]: 공동지출내역 테스트 코드 작성
